version: '3.8'

services:
  postgis-db-1:
    image: postgis/postgis:14-3.3-alpine
    container_name: postgis-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgis-test
    ports:
      - "5433:5433"
    networks:
      - backend
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - postgis_data:/var/lib/postgresql/data

  geoserver-1:
    image: oscarfonts/geoserver:latest
    container_name: geoserver-1
#    environment:
#      - GEOSERVER_ADMIN_PASSWORD=geoserver
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - GEOSERVER_DATA_DIR=/var/local/geoserver_data
    volumes:
      - ./geoserver_data:/var/local/geoserver_data
    depends_on:
      - postgis-db-1


  webgis-1:
#    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: webgis-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis-db-1:5432/postgis-test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - postgis-db-1

networks:
  backend:
    driver: bridge

volumes:
  postgis_data:
  geoserver_data:
